import { cn } from "@shared/ui/shadcn/lib/utils"
import type { Metadata } from "next"
import { Geist } from "next/font/google"
import "./globals.css"

const geist = Geist({ subsets: ["latin"], variable: "--font-sans" })

export const metadata: Metadata = {
   title: "Next.js App",
   description: "Generated by create next app",
}

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode
}>) {
   return (
      <html
         lang="en"
         className={cn("font-sans", geist.variable, "dark")}>
         <body>
            <main>{children}</main>
         </body>
      </html>
   )
}
